import Footer from "@/components/footer/page"
import Header from "@/components/header/page"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    default: "Next js - Code Evolution",
    template: "%s | CodeEvolution"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}

